---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: master
      port: {{ index .Values "containerPort" "http-port" }}
      targetPort: {{ index .Values "containerPort" "http-port" }}
    - name: slave
      port: {{ index .Values "containerPort" "jnlp-port" }}
      targetPort: {{ index .Values "containerPort" "jnlp-port" }}
  selector:
    app: {{ .Values.name }}
